import React from 'react'
import Admin from "@/components/Admin";
import { createBook, getBooks, getCategories } from '@/services/books.service'
import Head from 'next/head';

export default function admin({categoriesData}) {
  return (
    <>
     <Head>
      <title>My Library</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Admin categoriesData={categoriesData}/>
    </>
  )
}

export async function getServerSideProps({ req: { cookies ,headers}, resolvedUrl }) {

  const categoriesResponse = await getCategories();
  
  if (categoriesResponse?.status) {
    return { props: { categoriesData: categoriesResponse.data.map(category => Object.assign({}, { label: category.name, value: category.id })) } }
  } else {
    return { props: {} }
  }
}
