import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { format } from 'path'
import { useState } from 'react'


export default function Home() {
  const [form,setForm] = useState({
    role:''
  });


  const createRole = async (data) => {
    try{
      fetch('http://localhost:3000/api/create',{
        body : JSON.stringify(data),
        headers: {
          'Content-type': 'application/json'
        },
        method:"POST"
      }).then(()=>{
        setForm({role:''})
      })
    }catch(err){
      console.log(err)
    }
  }

  const handleSubmit =async (data)=>{
     try{

      createRole(data)

     }catch(err){
      console.log(err)
     }

  }


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/* <div className='mt-10 p-10 bg-slate-600'>Hello World!</div> */}
        <form className='w-auto min-w-[25%] max-w-min mx-auto space-y-6 flex flex-col items-stretch' onSubmit={e=>{
          e.preventDefault()
         handleSubmit(form);
        }}>
          <input className='border-2 rounded border-gray-600 p-1' type="text" value={form.role} onChange={e=>setForm({...format,role:e.target.value})} />
          <button className='bg-blue-400 text-white rounded p-1' type='submit'>Submit </button>
        </form>
      </main>
    </>
  )
}
