import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { format } from "path";
import { useState } from "react";
import Landing from "@/components/Landing";

export default function Home() {
  const [form, setForm] = useState({
    role: "",
  });

  // const createRole = async (data) => {
  //   try {
  //     fetch("http://localhost:3000/api/create", {
  //       body: JSON.stringify(data),
  //       headers: {
  //         "Content-type": "application/json",
  //       },
  //       method: "POST",
  //     }).then(() => {
  //       setForm({ role: "" });
  //     });
  //   } catch (err) {
  //     console.log(err);
  //   }
  // };

  // const handleSubmit = async (data) => {
  //   try {
  //     createRole(data);
  //   } catch (err) {
  //     console.log(err);
  //   }
  // };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Landing />
    </>
  );
}
